### ISSUE TITLE
Completion/command history tip

### ISSUE THREAD

**Issue by dbohdan** [gloriousfutureio/windows#1]
Heya! I saw your project on #tcl. You probably don't want rlwrap. You can also become a cool person by installing one of the following:
* [tclreadline](https://wiki.tcl.tk/5632) (compiled, advanced completion)
* [eltclsh](https://wiki.tcl.tk/11176) (compiled, beginner-friendly, somewhat less advanced completion)
* [pure-Tcl readline2](https://wiki.tcl.tk/20215) (pure Tcl but requires either Expect or Tclx, limited completion)
* [Tkcon](https://wiki.tcl.tk/1878) (pure Tcl, okay completion, GUI-only, looks ugly on Linux/FreeBSD)

All of the above are in Debian's/Ubuntu's package repositories. If you use Windows, as the name of this repo suggests, have a look at Tkcon first. If you're on *nix, try out eltclsh and tclreadline (Debian package `tcl-tclreadline`) to see whose completion you like more.

**Comment by dbohdan** [comment]
So much for emojis in the title.

**Comment by anxiousmodernman** [comment]
Hey! Thanks for the suggestions. I did try eltclsh, but I couldn't figure out how to change the prompt.

tclreadline looks like something I need to try instead. I was contemplating doing some funky scripting to put the standard procs into rlwrap, but a real tcl-focused program is probably going to be better.

Also, "windows" is kind of a joke, but mostly refers to Tk being a framework for "windowed" programs. This repo will be a grab bag of scripts while I learn Tcl and aggressively spam my friends about it.

**Comment by anxiousmodernman** [comment]
:cool: :sunglasses:

**Comment by anxiousmodernman** [comment]
I use Arch. Found it in AUR: https://aur.archlinux.org/packages/tclreadline/

This is definitely what I was looking for.

**Comment by dbohdan** [comment]
You're welcome! I see that the version of tclreadline in AUR is the original from 2001 with a minor patch. It should be fine, but you'll probably have a better experience with a more recent fork. I recommend [Flightaware's](https://github.com/flightaware/tclreadline/releases) as the most up-to-date on features and bug fixes. (Disclosure: I have contributed to it.)
